host: master.shopee_mkt_ap_meta.mysql.cloud.test.shopee.io:6606
user: opa_test
passwd: bDUZvrx3adusT_VotFC1
dbname: shopee_mkt_ap_meta_id_db
conn:
  maxidle: 50
  maxopen: 120

#host: master.shopee_mkt_ap_meta.mysql.cloud.test.shopee.io:6606
#user: opa_test
#passwd: bDUZvrx3adusT_VotFC1
#dbname: shopee_mkt_ap_settlement_id_db
#conn:
#  maxidle: 50
#  maxopen: 120

#host: master.8382589fe63b34a4.mysql.cloud.test.shopee.io:6606
#user: opa_test
#passwd: bDUZvrx3adusT_VotFC1
#dbname: shopee_mkt_ap_wallet_id_db
#conn:
#  maxidle: 50
#  maxopen: 120

#host: 127.0.0.1:6606
#user: root
#passwd: 123456@789
#dbname: ftgo_account_db
#conn:
#  maxidle: 50
#  maxopen: 120